---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [24, 25, 26, 27]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: export
      - run: make rebar3-install
      - run: make warnings
      - run: make check
      - run: make eunit
